### ISSUE TITLE
Placeholder images break https

### ISSUE THREAD

**Issue by mrPjer** [infinum/phrasing_plus#1]
Placeholder images are loaded over http://, causing the browser to complain on sites loaded over https because certain resources are included over non-secure connections.

It seems that the host you are using (placehold.it) supports SSL so this could be fixed by making the URIs protocol agnostic.

However, I'd suggest serving that placeholder image locally - this way sites can be developed offline, there is no metadata leak and  there are no dependencies on 3rd party services.

**Comment by DamirSvrtan** [comment]
I've released this in version 0.0.13.

Thnx for creating the issue & the pull request.
